<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Target;

class TargetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $targets = [
            [
                'code' => 'HSE.222-014.01',
                'indicator' => 'Comply with regulation about safety and DP',
                'calculation' => 'Jumlah regulasi yang sudah di evaluasi : jumlah regulasi yang sudah taat',
                'supporting_document' => 'Analisa Regulasi dan Action Plan perbaikan',
                'period' => 'Annual',
                'unit' => '%',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Persentasi ketaatan terhadap peraturan yang berkaitan dengan K3',
                'target_unit_id' => 1,
            ],
            [
                'code' => 'HSE.222-014.02',
                'indicator' => 'Comply terhadap standard BSJ (Zen-Z-Zai, Safety global std, IMD stndard)',
                'calculation' => 'Standard BSJ yang belum taat (comply) dilakukan perbaikan',
                'supporting_document' => 'Evaluasi standard BSJ',
                'period' => 'Quarter',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Persentasi ketaatan terhadap peraturan yang berkaitan dengan K3',
                'target_unit_id' => 2,
            ],
            [
                'code' => 'HSE.222-014.03',
                'indicator' => 'Comply terhadap peraturan KLHK tentang Karhutla',
                'calculation' => 'Daftar peralatan KARHUTLA yang terdapat dalam regulasi dilakukan perbaikan',
                'supporting_document' => 'Analisa Regulasi',
                'period' => 'Monthly',
                'unit' => '%',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Permentan No. 05 th 2028 Pembukaan dan / atau pengolahan lahan perkebunan tanpa membakar',
                'target_unit_id' => 3,
            ],
            [
                'code' => 'HSE.222-014.04',
                'indicator' => 'Area hotwork sesuai standard',
                'calculation' => 'Perbandingan antara standard  Hot work vs Actual ',
                'supporting_document' => 'Perbandingan antara standard  Hot work vs Actual',
                'period' => 'Semester',
                'unit' => '%',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => '',
                'target_unit_id' => 4,
            ],
            [
                'code' => 'HSE.222-014.05',
                'indicator' => 'P2K3',
                'calculation' => 'Kegiatan meeting P3K3 dan Laporan P2K3 ke Pemerintah',
                'supporting_document' => 'Notulen meeting P3K3, Absensi dan Laporan ke pemerintah',
                'period' => 'Quarter',
                'unit' => 'Freq/ th',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Kegiatan Sekretariat P2K3',
                'target_unit_id' => 5,
            ],
            [
                'code' => 'HSE.222-014.06',
                'indicator' => 'Perbaikan Kegiatan Drill',
                'calculation' => 'Permasalahan yang di identifikasi saat kegiatan drill bisa di selesaikan',
                'supporting_document' => 'Evaluasi simulasi keadaan Darurat dan dokumen perbaikan',
                'period' => 'Quarter',
                'unit' => '%',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => '',
                'target_unit_id' => 6,
            ],
            [
                'code' => 'HSE.222-014.07',
                'indicator' => 'Risk Assesement - Machinery',
                'calculation' => 'Jumlah Mesin yang ada di BSKP : jumlah mesin yang sudah di revisi RA',
                'supporting_document' => 'Summary RA  Mesin(rencana vs actual)',
                'period' => 'Annual',
                'unit' => 'Mesin',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Target dan aktual pembuatan RA mesin',
                'target_unit_id' => 7,
            ],
            [
                'code' => 'HSE.222-014.08',
                'indicator' => 'Risk Assesement - Task',
                'calculation' => 'Jumlah RA yang akan direvisi : jumlah RA yang sudah di revisi',
                'supporting_document' => 'Summary RA (rencana vs actual)',
                'period' => 'Monthly',
                'unit' => 'Kegiatan',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Target dan aktual pembuatan RA task',
                'target_unit_id' => 8,
            ],
            [
                'code' => 'HSE.222-014.09',
                'indicator' => 'Fire Risk Assessment',
                'calculation' => 'Jumlah RA (fire) yang akan direvisi : jumlah RA (fire) yang sudah di revisi',
                'supporting_document' => 'Summary RA (rencana vs actual)',
                'period' => 'Monthly',
                'unit' => 'Lokasi',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Fire Risk Assessment dibagi di data per lokasi',
                'target_unit_id' => 9,
            ],
            [
                'code' => 'HSE.222-014.10',
                'indicator' => 'Kegiatan inspeksi  oleh Karyawan yang memiliki sertifikasi dari Kementrian Tenaga Kerja',
                'calculation' => 'Terget inspeksi dan pelaksaan inspeksi',
                'supporting_document' => 'Log Inspeksi',
                'period' => 'Quarter',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Inspeksi Safety Manager, Inspeksi Safety rule',
                'target_unit_id' => 10,
            ],
            [
                'code' => 'HSE.222-014.11',
                'indicator' => 'Kegiatan inspeksi  oleh management',
                'calculation' => 'Terget inspeksi dan pelaksaan inspeksi',
                'supporting_document' => 'Log Inspeksi',
                'period' => 'Quarter',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Inspeksi Safety Manager dan PD',
                'target_unit_id' => 11,
            ],
            [
                'code' => 'HSE.222-014.12',
                'indicator' => 'Inspeksi yang berkaitan dengan Listrik',
                'calculation' => 'Terget inspeksi dan pelaksaan inspeksi',
                'supporting_document' => 'Log Inspeksi',
                'period' => 'Quarter',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => '',
                'target_unit_id' => 12,
            ],
            [
                'code' => 'HSE.222-014.13',
                'indicator' => 'Inspeksi yang berkaitan dengan K3 secara umum',
                'calculation' => 'Terget inspeksi dan pelaksaan inspeksi',
                'supporting_document' => 'Log Inspeksi',
                'period' => 'Quarter',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => '',
                'target_unit_id' => 13,
            ],
            [
                'code' => 'HSE.222-014.14',
                'indicator' => 'Maintenance FA',
                'calculation' => 'semua FA yang ada di BSKP di lakukan pemeliharaan ',
                'supporting_document' => 'BAP Meintenence oleh pihak ke-3',
                'period' => 'Annual',
                'unit' => '%',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => '',
                'target_unit_id' => 14,
            ],
            [
                'code' => 'HSE.222-014.15',
                'indicator' => 'Training KY Praktek dan Mandiri',
                'calculation' => 'Bulan dan Jlh TK yang akan di Training',
                'supporting_document' => 'Absen  dan In-house education / Training record',
                'period' => 'Monthly',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => '',
                'target_unit_id' => 15,
            ],
            [
                'code' => 'HSE.222-014.16',
                'indicator' => 'Training Hot work',
                'calculation' => 'Bulan dan Jlh TK yang akan di Training',
                'supporting_document' => 'Absen  dan In-house education / Training record',
                'period' => 'Annual',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Jumlah Mekanik di WS yang di berikan training',
                'target_unit_id' => 16,
            ],
            [
                'code' => 'HSE.222-014.17',
                'indicator' => 'Training confice space',
                'calculation' => 'Bulan dan Jlh TK yang akan di Training',
                'supporting_document' => 'Absen  dan In-house education / Training record',
                'period' => 'Annual',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Jumlah Mandor Factory + TK di Factory yang di berikan training',
                'target_unit_id' => 17,
            ],
            [
                'code' => 'HSE.222-014.18',
                'indicator' => 'Training Listrik, LOTO',
                'calculation' => 'Bulan dan Jlh TK yang akan di Training',
                'supporting_document' => 'Absen  dan In-house education / Training record',
                'period' => 'Annual',
                'unit' => 'Freq',
                'weighting' => '10%',
                'trend' => 'Positif',
                'employee_id' => 1,
                'date' => '2024-01-08 01:49:17',
                'detail' => 'Jumlah Mekanik di WS yang di berikan training',
                'target_unit_id' => 18,
            ],
        ];

        foreach ($targets as $target) {
            Target::factory()->create($target);
        }
    }
}
